# Generated by Django 6.0.5 on 2026-05-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='content/partners/')),
            ],
        ),
        migrations.CreateModel(
            name='CuratedMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='content/makes/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Protect what you love.', max_length=200)),
                ('hero_subtitle', models.TextField(default="Houston's trusted choice for premium auto care.")),
                ('vehicles_protected', models.CharField(default='55,078', max_length=50)),
                ('pain_points_title', models.CharField(default="Without the right team, the right products, and the right process, you're left dealing with:", max_length=200)),
                ('standard_title', models.CharField(default='You Want the Best for What Matters', max_length=200)),
                ('standard_description', models.TextField()),
                ('standard_image', models.ImageField(blank=True, null=True, upload_to='content/standard/')),
                ('about_title', models.CharField(default='PREMIERE AUTOMOTIVE DETAILING', max_length=200)),
                ('about_description', models.TextField()),
                ('stat_1_number', models.CharField(default='2,500+', max_length=50)),
                ('stat_1_text', models.CharField(default='Cars Detailed', max_length=100)),
                ('stat_2_number', models.CharField(default='8+', max_length=50)),
                ('stat_2_text', models.CharField(default='Years of Experience', max_length=100)),
                ('stat_3_number', models.CharField(default='30+', max_length=50)),
                ('stat_3_text', models.CharField(default='Certified & Trusted Experts', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='content/promotions/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('date_posted', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_features', to='content.homepageconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_points', to='content.homepageconfig')),
            ],
        ),
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_items', to='content.homepageconfig')),
            ],
        ),
    ]
