# Generated by Django 6.0.5 on 2026-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homepageconfig_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='address',
            field=models.CharField(default='4444 W 70th St, Edina, MN 55435', max_length=255),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='email',
            field=models.EmailField(default='info@optumcarcare.com', max_length=254),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='phone',
            field=models.CharField(default='651-706-9995', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='working_hours_mon_fri',
            field=models.CharField(default='10:00 AM to 6:00 PM (Appointment Only)', max_length=150),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='working_hours_sat',
            field=models.CharField(default='11:00 AM to 2:00 PM (Appointment Only)', max_length=150),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='working_hours_sun',
            field=models.CharField(default='Closed', max_length=150),
        ),
        migrations.AlterField(
            model_name='brandpartner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='content/partners/'),
        ),
        migrations.AlterField(
            model_name='curatedmake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/makes/'),
        ),
    ]
