# Generated by Django 6.0.5 on 2026-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_homepageconfig_address_homepageconfig_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='banner_cta_subtitle',
            field=models.CharField(default='We do it right the first time.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='banner_cta_title',
            field=models.CharField(default='WHATEVER PROTECTION OR ENHANCEMENT YOUR VEHICLE NEEDS...', max_length=255),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='intro_description',
            field=models.TextField(default="With Houston's unpredictable roads and intense heat, protection isn't optional—it's essential. That's why many vehicle owners want top-quality care for their cars and trucks. But finding a trusted expert to protect and maintain them can be challenging."),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='intro_title',
            field=models.CharField(default='You Want the Best for What Matters', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='partners_description',
            field=models.TextField(default='Pristine Detail is proud to be a certified installer in automotive paint protection film and window tinting along with vinyl wrapping and other services! By using some of the best products in the industry, we guarantee and stand by our products and craftsmanship.'),
        ),
    ]
