# Generated by Django 6.0.5 on 2026-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homepageconfig_banner_cta_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/banners/'),
        ),
    ]
