# Generated by Django 6.0.5 on 2026-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_homepageconfig_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='content/about/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='content/about/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/contact/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/hero/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/intro/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='review_count',
            field=models.CharField(default='205', max_length=20),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='review_rating',
            field=models.CharField(default='5.0', max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='content/avatars/'),
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='partners_description',
            field=models.TextField(default='Pristine Detail is proud to be a certified installer in automotive paint protection film and window tinting along with vinyl wrapping and other services! By using some of the best products in the industry, we guarantee and standby our products and craftsmanship.'),
        ),
    ]
