# Generated by Django 6.0.5 on 2026-06-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_processstep_studioexperienceconfig_studiogalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='The best automotive spa experience at Optum Studio', max_length=255)),
                ('hero_description', models.TextField(default='Optum Studio offers the highest level of detail and protection in Bengaluru. Our meticulous process ensures your vehicle receives the ultimate care, leaving it looking better than the day it left the showroom floor.')),
                ('hero_video_url', models.URLField(default='https://cdn.pixabay.com/video/2021/08/04/83866-584733364_large.mp4')),
            ],
        ),
    ]
