# Generated by Django 6.0.5 on 2026-06-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_processpageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='processpageconfig',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/process/'),
        ),
    ]
