# Generated by Django 6.0.5 on 2026-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_processpageconfig_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='google_review_link',
            field=models.URLField(blank=True, help_text='Link to your Google Reviews page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Override the default phone number for WhatsApp. Keep empty to use the main phone number.', max_length=50, null=True),
        ),
    ]
