# Generated by Django 6.0.5 on 2026-06-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_homepageconfig_google_review_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='faqs_eyebrow',
            field=models.CharField(default='Knowledge Base', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='faqs_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='intro_eyebrow',
            field=models.CharField(default='You Want the Best for What Matters', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='makes_eyebrow',
            field=models.CharField(default='Trusted By Owners Of', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='makes_title',
            field=models.CharField(default='World-Class Engineering', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='partners_eyebrow',
            field=models.CharField(default='Our Partners & Certified Installers', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='partners_title',
            field=models.CharField(default='Industry Standard Products', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='services_description',
            field=models.TextField(default='From meticulous paint correction to cutting-edge ceramic protection, our comprehensive suite of services ensures your vehicle remains in concourse condition.'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='services_eyebrow',
            field=models.CharField(default='Our Expertise', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='services_title',
            field=models.CharField(default='Mastery in Every Detail', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='standard_eyebrow',
            field=models.CharField(default='The Standard', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='testimonials_eyebrow',
            field=models.CharField(default='Client Experiences', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='testimonials_title',
            field=models.CharField(default='Words From Our Patrons', max_length=200),
        ),
    ]
