# Generated by Django 6.0.5 on 2026-06-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_homepageconfig_faqs_eyebrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageconfig',
            name='standard_image',
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='standard_image_after',
            field=models.ImageField(blank=True, null=True, upload_to='content/standard/after/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='standard_image_before',
            field=models.ImageField(blank=True, null=True, upload_to='content/standard/before/'),
        ),
    ]
