# Generated by Django 6.0.5 on 2026-05-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tag_line', models.CharField(blank=True, max_length=200)),
                ('hero_description', models.TextField()),
                ('hero_image', models.ImageField(upload_to='services/hero/')),
                ('manifesto_title', models.CharField(default='THE ART OF THE INSTALL', max_length=200)),
                ('manifesto_description', models.TextField(blank=True)),
                ('manifesto_media', models.ImageField(blank=True, null=True, upload_to='services/manifesto/')),
                ('standards_title', models.CharField(default='UNCOMPROMISED STANDARDS IN EVERY MICRON', max_length=200)),
                ('standards_description', models.TextField(blank=True)),
                ('standards_image', models.ImageField(blank=True, null=True, upload_to='services/standards/')),
                ('cta_text', models.CharField(default='GET A BESPOKE QUOTE', max_length=100)),
                ('cta_link', models.CharField(default='/contact', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('before_image', models.ImageField(upload_to='services/before_after/')),
                ('after_image', models.ImageField(upload_to='services/before_after/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_afters', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStandardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_items', to='services.service')),
            ],
        ),
    ]
