# Generated by Django 6.0.5 on 2026-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_meta_description_service_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='servicebeforeafter',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/before_after/'),
        ),
        migrations.AlterField(
            model_name='servicebeforeafter',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/before_after/'),
        ),
    ]
