# Generated by Django 6.0.5 on 2026-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Premium Car Protection Services.', max_length=255)),
                ('hero_description', models.TextField(default='Discover our comprehensive range of high-end vehicle protection and detailing services designed to preserve your investment and elevate your driving experience.')),
            ],
        ),
    ]
