# Generated by Django 6.0.5 on 2026-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicespageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube URL to autoplay in the home page service card (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)', null=True),
        ),
    ]
