# Generated by Django 6.0.5 on 2026-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_youtube_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='manifesto_youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL for Craft Manifesto section (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)', null=True),
        ),
    ]
